package com.opensource.svgaplayer.utils

object Source2UrlMapping {

    // SVGA resources (key and value kept exactly as in svgaMp4UrlMap.json)
    val SVGA_MAP: Map<String, String> = mapOf(
        "blindbox/room_blind_box_banner_level_1.svga" to "https://res.lukeelive.com/FqTf7CBnbrl4XsVYX3FOg-mPIVA0?imageslim",
        "blindbox/room_blind_box_banner_level_1_ar.svga" to "https://res.lukeelive.com/Fg6G8S6nKuTW2rbRO8by78KwY-Q1?imageslim",
        "blindbox/room_blind_box_banner_level_2.svga" to "https://res.lukeelive.com/FsINtzf1Ox1mKMJT4Ogca1BhGSB7?imageslim",
        "blindbox/room_blind_box_banner_level_2_ar.svga" to "https://res.lukeelive.com/FjfN_OW4wtnX-TNnDClLDx41qkOm?imageslim",
        "blindbox/room_blind_box_banner_level_3.svga" to "https://res.lukeelive.com/FvUKI-cbdlek39L5nMtGJaYXZ5sg?imageslim",
        "blindbox/room_blind_box_banner_level_3_ar.svga" to "https://res.lukeelive.com/Fj9x76wsovZIqGcejBE1UixWVasW?imageslim",
        "call_match_receive.svga" to "https://res.lukeelive.com/Fkvsw0YDcEWLhljrWVrFsadU9Od1?imageslim",
        "full_notice/rank_charm_banner.svga" to "https://res.lukeelive.com/Fm_AUWLC3htNTkangwMPMs4tK5g9?imageslim",
        "full_notice/rank_room_banner.svga" to "https://res.lukeelive.com/FnRjPXqxXmzn5GodH6oeLX0R62Ud?imageslim",
        "full_notice/rank_wealth_banner.svga" to "https://res.lukeelive.com/Fr4eeqXqxA4bPH-2lZftW6HfF2bR?imageslim",
        "giftCombo/gift_combo_0.svga" to "https://res.lukeelive.com/FgyBzF2CA9-VrR6saYpC-McQe2z0?imageslim",
        "giftCombo/gift_combo_1000.svga" to "https://res.lukeelive.com/FgN2tVDFmIbhpedvJmt3sqBPK7Ru?imageslim",
        "giftCombo/gift_combo_500.svga" to "https://res.lukeelive.com/FpeZhnez6T_gAT3O0KjDmEzvoEsS?imageslim",
        "giftCombo/send_gift.svga" to "https://res.lukeelive.com/FvRS4nrf3wGx6NcAPVjcWrVnWPga?imageslim",
        "giftCombo/send_gift_circle.svga" to "https://res.lukeelive.com/FrsZq6vMGkFIAew03A1ijiZnKjOL?imageslim",
        "giftRefund/gift_refund_1000.svga" to "https://res.lukeelive.com/FtH4U3oMedmvp3pwU1lwqDqfH7S_?imageslim",
        "giftRefund/gift_refund_50.svga" to "https://res.lukeelive.com/Fo0mrlqB0gYIEorDJGdDhqodLCt9?imageslim",
        "giftRefund/gift_refund_500.svga" to "https://res.lukeelive.com/FlMhqDyufWJAl2W7WwYoNyDxptXB?imageslim",
        "home_audio_live.svga" to "https://res.lukeelive.com/FqWYfWOCwivi4zqwIkubZr3t6xJf?imageslim",
        "home_audio_live_circle.svga" to "https://res.lukeelive.com/FoOdE-t1LqiyRb1qz0V3TC6oWEpK?imageslim",
        "home_room_running.svga" to "https://res.lukeelive.com/FhI4lJJDsNj130uInTWQWDJYL508?imageslim",
        "live/home_live_pager_online_num.svga" to "https://res.lukeelive.com/FuE-ym3vdrbQ-8mwlba2FdsxZ-_Q?imageslim",
        "live/home_live_pager_online_num_white.svga" to "https://res.lukeelive.com/FrPdtjrjnnt43pzwDgF6KwrxQ30z?imageslim",
        "live/ic_home_live_room_pk.svga" to "https://res.lukeelive.com/FvfhuQo_rPPsryM8dupNMvzffvSS?imageslim",
        "loading.svga" to "https://res.lukeelive.com/FlqZmNr7JDvu-i88UIEhkLTiJIaN?imageslim",
        "luckyGiftBanner/luck_gift_banner_100.svga" to "https://res.lukeelive.com/FhTlxVQWhIByJoxVADeNGtMpDGFQ?imageslim",
        "luckyGiftBanner/luck_gift_banner_1000.svga" to "https://res.lukeelive.com/FiPy9e1y4SuNJ5iofcnbtt24OyxU?imageslim",
        "luckyGiftBanner/luck_gift_banner_500.svga" to "https://res.lukeelive.com/Fuy3pNgsGMw6DheFEb3g5lcW4KLq?imageslim",
        "mic/mic_speak.svga" to "https://res.lukeelive.com/Fr7pwaI4o95evF1lyKauLfTSCg7B?imageslim",
        "minimizeState/audio.svga" to "https://res.lukeelive.com/FlhkOIv1345r62WlYgDcpUkLrYmX?imageslim",
        "music/music_cd.svga" to "https://res.lukeelive.com/Fk2BM2vOPptUbZr29s-ipfXWrqZW?imageslim",
        "music/music_cd_mini.svga" to "https://res.lukeelive.com/FoBz3YChN97SzqxftNfyv96DM8mo?imageslim",
        "pk/pk_line.svga" to "https://res.lukeelive.com/Foz7FDJz1u4fmupCZ5hDtllzVIXT?imageslim",
        "pk/pk_punish_effect.svga" to "https://res.lukeelive.com/Fil1W2cN-iQl9KTgJcVifS_J_9ES?imageslim",
        "pk/pk_rabbit_draw.svga" to "https://res.lukeelive.com/FiqDfwkymnAa-bvFWBd6-t96rLP2?imageslim",
        "pk/pk_rabbit_fail.svga" to "https://res.lukeelive.com/FsgrsLenvNSSD_m_CfHdDKW2kqsS?imageslim",
        "pk/pk_rabbit_run_left.svga" to "https://res.lukeelive.com/FnZzsCqL0HXwgBHZKZYXbezxvFTv?imageslim",
        "pk/pk_rabbit_run_right.svga" to "https://res.lukeelive.com/FoloO3x9zzGnuY_CITpXWqOJGEwK?imageslim",
        "pk/pk_rabbit_success.svga" to "https://res.lukeelive.com/Fi7TiNghVJKQ-yoh56OGoLFf5KTl?imageslim",
        "pk/pk_random_match.svga" to "https://res.lukeelive.com/FvMwNQUc5gyPc_fj89tPLJh68gha?imageslim",
        "plantpea/plantbean.svga" to "https://res.lukeelive.com/FlHWxW7CYuB1JmOvpCmsAzAL8SWe?imageslim",
        "plantpea/plantbeanreward.svga" to "https://res.lukeelive.com/Fq2I21FLwGgdFkxBe12LccxuZwG1?imageslim",
        "rank_reward.svga" to "https://res.lukeelive.com/FphkBwZmpS0gjSZeqfQaQhoI156R?imageslim",
        "rocket/rocket_1.svga" to "https://res.lukeelive.com/FunKZltNzrEhyu479PmFsb6UPq2O?imageslim",
        "rocket/rocket_2.svga" to "https://res.lukeelive.com/FkpN1KdkGIipu2pU_KGOUAZ0dezt?imageslim",
        "rocket/rocket_3.svga" to "https://res.lukeelive.com/FoIavUiF9_KTNvupc4N7gUMhgud7?imageslim",
        "rocket/rocket_4.svga" to "https://res.lukeelive.com/FjPTxe4_TKDGfQZBrSKNqB5JtvkT?imageslim",
        "rocket/rocket_5.svga" to "https://res.lukeelive.com/FoGQOo42fhiZmNzkGvWolaGQnKM5?imageslim",
        "rocket/rocket_6.svga" to "https://res.lukeelive.com/Fg3RQh8jYC-XI9k3Tl1Rn-EhVFhT?imageslim",
        "rocket/rocket_7.svga" to "https://res.lukeelive.com/Frutb2NoaorSEJKXDHS5N18cHYvr?imageslim",
        "rocket/rocket_transition.svga" to "https://res.lukeelive.com/FvmYFprXSK-Rx0NfYFoQyMtSUtTz?imageslim",
        "rocket/room_rocket_gift_banner.svga" to "https://res.lukeelive.com/FteX9RK3bZmlQrKiwCG91-mtOMms?imageslim",
        "roomGift/ic_room_gift.svga" to "https://res.lukeelive.com/Fs65NU7ybKEacGWBZn3BOsk7D1SC?imageslim",
        "roomMode/room_mode_birthday_aperture.svga" to "https://res.lukeelive.com/FpjhYwLEDf-NnhYNVccpaBKnsdjL?imageslim",
        "roomMode/room_mode_cp_cp_line.svga" to "https://res.lukeelive.com/FtepK1b-j8RDXrJQtG_ypZRTnh7T?imageslim",
        "roomMode/room_mode_cp_normal_line.svga" to "https://res.lukeelive.com/FqVeqSgqbW6Oc1Q6fCjBzE_XClXm?imageslim",
        "roomMode/room_mode_draw_lots_16_turntable.svga" to "https://res.lukeelive.com/Fu7zHC43vep3JcrngRPnLxf7jP4b?imageslim",
        "roomMode/room_mode_draw_lots_4_8_turntable.svga" to "https://res.lukeelive.com/FvBmsp_CDW-f3sLNLSS-nZ3zUrkG?imageslim",
        "roomMode/room_mode_draw_lots_lottery_avatar_bg.svga" to "https://res.lukeelive.com/FtVmhryHo9Ni45NvGpVHXGisTW3Y?imageslim",
        "roomMode/room_mode_draw_lots_lottery_select.svga" to "https://res.lukeelive.com/FhFyUvHTzKx5PVMGmsUA2Q6cCFY2?imageslim",
        "roomMode/room_mode_draw_lots_lottery_top.svga" to "https://res.lukeelive.com/FkFdLd2LM-wKLmy9oiajUREscM3R?imageslim",
        "roomMode/room_mode_draw_lots_start_btn.svga" to "https://res.lukeelive.com/Fn6iP59y8WvHLIshBbAGiaP7paGm?imageslim",
        "roomMode/room_mode_draw_lots_start_btn_click.svga" to "https://res.lukeelive.com/FjA2YQA5JdgukIijoy7pCbmyqBik?imageslim",
        "smashEgg/smash_golden_egg_lottery.svga" to "https://res.lukeelive.com/FpKclCGMAVOPpOogQh1kLXUZYG5A?imageslim",
        "smashEgg/smash_sliver_egg_lottery.svga" to "https://res.lukeelive.com/FlpOOWBROkzeiRPjultmIklY9CFf?imageslim",
        "svip/svip_7_enter_room.svga" to "https://res.lukeelive.com/Fr8HfArHC0Jvu_dckanrlCW8ukmO?imageslim",
        "svip/svip_8_enter_room.svga" to "https://res.lukeelive.com/FmGoM_5QHWt3wgYYynV0oAVzay0r?imageslim",
        "svip/svip_8_online_notify.svga" to "https://res.lukeelive.com/FlLFVUe7QbHOxobws4cXCrLFK0iP?imageslim",
        "system_reward.svga" to "https://res.lukeelive.com/FmMRGCYAgIXa93PLqxm-bdLDqOXT?imageslim",
        "upMic/audio_room_notify_up_mic.svga" to "https://res.lukeelive.com/FjLrRICDy9ljy9eT1-wiUnCOj1wv?imageslim",
        "user/nick_valid_fail.svga" to "https://res.lukeelive.com/Flz0abX4gtntTRYk2ZJ7zB1QyFVZ?imageslim",
        "user/user_trace.svga" to "https://res.lukeelive.com/Fv1ez5PGNTnF_htOZxkLpbM7_4R9?imageslim",
        "user_sign_in_bg.svga" to "https://res.lukeelive.com/FswMyuvCeQ7Z57FihkyZ2XgOCg3M?imageslim",
        "user_upgrade_bg.svga" to "https://res.lukeelive.com/FpihFqahthUFnruyxHK-qNzkn_hi?imageslim",
        "xLuckyGift/gift_combo_0.svga" to "https://res.lukeelive.com/FgyBzF2CA9-VrR6saYpC-McQe2z0?imageslim",
        "xLuckyGift/gift_combo_1000.svga" to "https://res.lukeelive.com/FgN2tVDFmIbhpedvJmt3sqBPK7Ru?imageslim",
        "xLuckyGift/gift_combo_500.svga" to "https://res.lukeelive.com/FpeZhnez6T_gAT3O0KjDmEzvoEsS?imageslim",
        "xLuckyGift/gift_refund_1000.svga" to "https://res.lukeelive.com/FtH4U3oMedmvp3pwU1lwqDqfH7S_?imageslim",
        "xLuckyGift/gift_refund_50.svga" to "https://res.lukeelive.com/Fo0mrlqB0gYIEorDJGdDhqodLCt9?imageslim",
        "xLuckyGift/gift_refund_500.svga" to "https://res.lukeelive.com/FlMhqDyufWJAl2W7WwYoNyDxptXB?imageslim",
        "xLuckyGift/luck_gift_banner_100.svga" to "https://res.lukeelive.com/FhTlxVQWhIByJoxVADeNGtMpDGFQ?imageslim",
        "xLuckyGift/luck_gift_banner_1000.svga" to "https://res.lukeelive.com/FiPy9e1y4SuNJ5iofcnbtt24OyxU?imageslim",
        "xLuckyGift/luck_gift_banner_500.svga" to "https://res.lukeelive.com/Fuy3pNgsGMw6DheFEb3g5lcW4KLq?imageslim"
    )

    // MP4 resources (key and value kept exactly as in svgaMp4UrlMap.json)
    val MP4_MAP: Map<String, String> = mapOf(
        "gameBanner/audio_live_room_game_banner.mp4" to "https://res.lukeelive.com/FucaR-Z9o6zMQqs0WbInjVkKioMm?imageslim",
        "giftBanner/audio_live_room_gift_banner_1.mp4" to "https://res.lukeelive.com/Fo4MooombDHctoZjSbsKRiAyooV8?imageslim",
        "giftBanner/audio_live_room_gift_banner_2.mp4" to "https://res.lukeelive.com/FoK5uWLkrPD5FrQWy_DUtkPmjKoj?imageslim",
        "giftBanner/audio_live_room_gift_banner_3.mp4" to "https://res.lukeelive.com/FqiIO_eYOsPjA2j0IlC04JQQjLPN?imageslim",
        "giftBanner/audio_live_room_gift_banner_4.mp4" to "https://res.lukeelive.com/FiB57n4SuxrClj1sw4b0DiEcyRYo?imageslim",
        "giftBanner/audio_live_room_gift_banner_5.mp4" to "https://res.lukeelive.com/FqHSl6CNM9iLCbqCU-xXtM3Jsf9N?imageslim",
        "pk/vap/pk_room_bg.mp4" to "https://res.lukeelive.com/FnrtV30_Nwx0SopCIqt8l0jTJDQl?imageslim",
        "pk/vap/pk_settlement_arms.mp4" to "https://res.lukeelive.com/Ft4KmGv2N8q7unYxZNDim8PHVEn0?imageslim",
        "pk/vap/pk_settlement_bg.mp4" to "https://res.lukeelive.com/FiCsumHTro_1IQCuZRxMNxDNcRLS?imageslim",
        "pk/vap/pk_start.mp4" to "https://res.lukeelive.com/FqG3mKL-iQO4XlUEKc9HmYK8gUpP?imageslim",
        "rocketVap/rocket_1.mp4" to "https://res.lukeelive.com/FtQheDRMgmAYoKbmvGNirR-WgAJb?imageslim",
        "rocketVap/rocket_2.mp4" to "https://res.lukeelive.com/FotHtgZ6VInC4vhoFtcI3LFF4XkY?imageslim",
        "rocketVap/rocket_3.mp4" to "https://res.lukeelive.com/Fm0M3k3wqqoeRzqxA7EqwQh1Ub5d?imageslim",
        "rocketVap/rocket_4.mp4" to "https://res.lukeelive.com/Fm1iXawgH1b8_Q3WGGng7Ld5AVZD?imageslim",
        "rocketVap/rocket_5.mp4" to "https://res.lukeelive.com/FtdXaf0MVg65BS2Je2rHU0RVC659?imageslim",
        "rocketVap/rocket_6.mp4" to "https://res.lukeelive.com/FnpFMVK-wJZtg5bSUjBu9KOUOfQu?imageslim",
        "rocketVap/rocket_7.mp4" to "https://res.lukeelive.com/FhSsYTOPMuSLMgQyYTqCBf9zC0eI?imageslim"
    )

}